module.exports = {
    content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    plugins: [require('@tailwindcss/line-clamp')],
    theme: {
        extend: {
            boxShadow: {
                '2x': '0px 5px 6px rgba(15, 15, 15, 0.35), 0px 24px 80px rgba(37, 37, 37, 0.7)',
            },
            lineHeight: {
                14: '14px',
                17: '17px',
                22: '22px',
                28: '28px',
                46: '46px',
                94: '94px',
                120: '120%',
                130: '130%',
                136: '136%',
                140: '140%',
            },
            colors: {
                white: {
                    DEFAULT: '#FFFFFF',
                },
                green: {
                    DEFAULT: '#4aa5ff',
                    100: '#049282',
                },
                blue: {
                    DEFAULT: '#4aa5ff',
                    100: '#4aa5ff',
                },
                dark: {
                    100: '#193469',
                    200: '#070D18',
                },
                black: {
                    100: '#15151729',
                },
                gray: {
                    DEFAULT: '#828792',
                    100: '#F2F5FA',
                    200: '#F7F9FA',
                    300: '#FFFFFF80',
                    400: '#979798',
                    500: '#FFFFFF4D',
                    600: '#FFFFFF33',
                    700: '#27272B',
                    800: '#353538',
                },
                'vacancy-card-background': '#2B2B2E',
                'vacancy-btn': 'rgba(255, 255, 255, 0.2)',
                'vacancy-btn-text-color': 'rgba(255, 255, 255, 0.6)',
                'vacancy-card-divider': 'rgba(255, 255, 255, 0.1)',
                'vacancy-card-icon-bg': 'rgba(255, 255, 255, 0.14)',
                'vacancy-card-icon-text': '#A5A5A6',
                'vacancy-card-footer-bg': '#252527',
                'vacancy-card-footer-bg-active': '#4AA5FF',
                'vacancy-card-footer-border': '#37373A',
                'vacancy-card-footer-border-active': 'rgba(255, 255, 255, 0.4)',
                'blog-card-background': '#2B2B2E',
            },
            borderRadius: {
                6: '6px',
                8: '8px',
                12: '12px',
                20: '20px',
                24: '24px',
            },
            screens: {
                xss: '100px',
                sx: '320px',
                xs: '375px',
                msm: '435px',
                mmm: '459px',
                ms: '500px',
                sm: '576px',
                smm: '500px',
                ss: '650px',
                md: '768px',
                mmd: '800px',
                lg: '992px',
                xl: '1200px',
                xxl: '1536px',
            },
            gridTemplateColumns: {
                portfolio: 'repeat(auto-fit,minmax(250px,1fr))',
            },
            fontFamily: {
                sofia: ['Sofia Pro', 'sans-serif'],
                roboto: ['Roboto', 'sans-serif'],
                openSans: ['Open Sans', 'sans-serif'],
                greyCliff: ['Greycliff CF', 'sans-serif'],
            },
            fontSize: {
                32: '32px',
            },
            backdropBlur: {
                20: '20px',
                146: '146px',
            },
        },
    },
}
